# SITE CONFIGURATION
baseurl: ""
url: "https://tropico.fm"

# THEME-SPECIFIC CONFIGURATION
title: Tropico.FM # site's title
description: "Trópico 208 was formed as an artist collective of like minded individuals who celebrate the rich art & music of countries like Mexico, Brazil, Bahamas, Colombia, and more. From art showcases to music festivals, we seek to put local artists of color into the spotlight." # used by search engines
avatar: # Empty for no avatar in navbar
favicon: assets/favicon-96x96.png # Icon displayed in the tab

# Header and footer text
header_text: Boise's Newest Community Radio Project! # Change Blog header text
header_caption: 103.1 Tropico FM # Change Blog header text
header_feature_image: assets/img/header/header.jpeg
header_feature_image_responsive: true
footer_text: ©2022 Tropico.FM

# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/tropico.png # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true # Enable if using math markup
mermaid: true # Enable mermaid-js for sequence and diagrams
google_analytics: # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false # To respect the usage of cookies
color_theme: auto # auto, dark or light

# Comments
comments:
  disqus_shortname: # Your discus shortname for comments
  cusdis_app_id: # Your cusdis data-app-id
  utterances: # Enable by filling below information. For more info, go to https://utteranc.es
    repo: # your public comments repository (e.g. owner/repo)
    issue-term: # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  music:
    output: true
    permalink: /:collection/:name
  art:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude:
  [
    ".jekyll-cache",
    ".jekyll-metadata",
    ".idea",
    "vendor/*",
    "assets/node_modules/*",
  ]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
